baseURL = 'https://tno.github.io/awesome-sbom/'
languageCode = 'en-us'
title = 'Awsome-SBOM'

[outputs]
    home = ["HTML", "JSON"]



[params]
  description = "Awsome-SBOM"
  logo = "https://www.tno.nl/publish/pages/5604/tno-logo-1484x835_003_.jpg"
  tagline = "One stop shop for SBOM tooling information"
  welcome_file = "data/welcome.md"

[params.author]
    name = "TNO"
    image = "images/sbom_graphic.png"


[caches]
  [caches.images]
    dir = ':cacheDir/images'
